### ISSUE TITLE
Merging allOf references before validation

### ISSUE THREAD

**Issue by YOU54F** [pactflow/swagger-mock-validator#14]
`allOf`s cause pain in validation.

You can pre-process them 

https://github.com/YOU54F/oas-merge

Wonder if we should just add this as part of the tool

**Comment by mefellows** [comment]
Closing this off, the following PRs have addressed it via a much nicer and less invasive means:

- https://github.com/pactflow/swagger-mock-validator/pull/31
- https://github.com/pactflow/swagger-mock-validator/pull/32
- https://github.com/pactflow/swagger-mock-validator/pull/34

**Comment by mefellows** [comment]
The detailed explanation for all of keyword support now lives here: https://docs.pactflow.io/docs/bi-directional-contract-testing/contracts/oas/keyword-support
