### ISSUE TITLE
Release tags aren't being updated

### ISSUE THREAD

**Issue by YOU54F** [pactflow/swagger-mock-validator#27]
Latest release on npm is 12.1.0, latest tag is 11.3.0

**Comment by YOU54F** [comment]
cc @vwong 

Please note that you need to manually generate the GitHub release until we automate this. I've retrospectively done it to get up to date releases in GH for the released npm packages

Notes

1. Create a release from the tag in GitHub
  - Set it to `latest`
  - Click `Generate CHANGELOG` to fill out a changelog.
  - Click `Publish Release`

**Comment by vwong** [comment]
Ok, I'll remember to do this next time. Thanks for fixing it up retrospectively.

**Comment by YOU54F** [comment]
No worries, sorry, you shouldn't have to think about this, it should just be done automagically in CI.

Will get it sorted at some point
