### ISSUE TITLE
Support for publishing verification results to an internal broker

### ISSUE THREAD

**Issue by lpcruz** [pactflow/swagger-mock-validator#54]
👋🏽  Hey folks,

First - I recently discovered this tool and out-of-the-box, I think it's great and solves a problem that we have with verification with speed/ease.

I was digging around the docs and tried a few attempts via a `--publish` flag but I'm not entirely sure if this tool supports publishing verification results to an internal broker? Is that a possibility? 

If not, I'd be happy to fork this and experiment.

**Comment by YOU54F** [comment]
Have you seen https://github.com/pactflow/swagger-mock-validator/pull/53

**Comment by lpcruz** [comment]
> Have you seen #53

Ha! Well I'm a goon. Thanks @YOU54F !!!

**Comment by JP-Ellis** [comment]
Closing this as the duplicate has been identified :)
