### ISSUE TITLE
Negative scenario testing (allow testing 4xx, 5xx responses)

### ISSUE THREAD

**Issue by tl-madhulika-mitra** [pactflow/swagger-mock-validator#9]
For some tests the request body has missing information, or the authentication headers are skipped in order to get the 4XX response. But when this interaction is tested with BDCT there is an error on request body correctness. 

How can this be avoided, since in this case, the interaction is correct and just the response should be evaluated.

**Comment by mefellows** [comment]
We had an item on our backlog for this, I'm going to link the issues so we can better track this.

**Comment by mefellows** [comment]
Closed in #30
